# frozen_string_literal: true

source 'https://rubygems.org'

# ActiveSupport and rexml are only used for XML support
gem 'activesupport'
gem 'rake'
gem 'rexml'

gem "aws-msk-iam-sasl-signer"
gem 'karafka'

group :development, :test do
  gem 'byebug', platform: :ruby
  gem 'karafka-testing'
  gem 'rspec'
  gem 'simplecov'
end
